# server port config
server:
  port: 8769
  
# oracle driver config
spring:  datasource:    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
    username: ERP_BOMB
    password: ERP_BOMB
  
# jpa config
  jpa:
    generate-ddl: false
    show-sql: true
    database: oracle
    database-platform: org.hibernate.dialect.Oracle10gDialect
    open-in-view: false
#logging:
#  level:
#    '[org.hibernate]': info